language: php

php:
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - phpenv rehash
  - php artisan key:generate
  
script:
  - vendor/bin/phpunit --coverage-text
